### ISSUE TITLE
Альтернативы электронным компонентам

### ISSUE THREAD

**Issue by GWan1234** [koptserg/e-monitor#1]
Is it possible to replace it with bmp280.

https://aliexpress.ru/item/33000261871.html?sku_id=67065052190&spm=a2g2w.productlist.0.0.17895baerVcNhx
or
https://aliexpress.ru/item/1005001621733499.html?sku_id=12000016846125862&spm=a2g2w.productlist.0.0.17895baerVcNhx

As far as I know, it contains temperature and humidity sensors and pressure sensors. The accuracy may be reduced, 

but it is cheaper. Can it be supported?

**Comment by koptserg** [comment]
There is no humidity parameter in the BMP280 sensor, only pressure and temperature. At the moment, BMP280 is not supported.
