### ISSUE TITLE
Allocation of image buffer

### ISSUE THREAD

**Issue by pedroke** [koptserg/e-monitor#2]
.. just a remark.. I noticed in your code you allocate image buffer in display drivers e.g. epd2in9.c this way:

unsigned char image[672];
PaintPaint(image, 0, 0);

inside init functions..
Isn't the buffer created on the stack instead of heap? I don't think it's safe to use it when the the init function finishes..

**Comment by koptserg** [comment]
in the EpdInitFull() and EpdInitPartial() functions, the image[672] buffer is declared and the initialization of PaintPaint(image, 0, 0) is started
in https://github.com/koptserg/e-monitor/blob/main/Source/epdpaint.h#L43 is declared global.

**Comment by pedroke** [comment]
:) sorry I missed the global extern declaration ..

**Comment by koptserg** [comment]
Thanks for the question! Indeed, when initializing PaintPaint(image, 0, 0), no buffer was reserved in RAM. There will be fixes in the next release.

**Comment by pedroke** [comment]
Thank you for sharing! I actually based my next project - kind of a zigbee status panel on your epd driver. I don't have it yet on the github, but it will be soon.. But, I was wondering, because when I compared some parts, especially initialization of 2.9inchV2 with the examples provided by waveshare I found some essential differences, so I rather based mine on the waveshare code.. When I put it on github, we can compare our versions, I'm not sure which one would be more suitable.. I'm not sure why there are differences in your code when compared with waveshare.. So we can fine tune later :)
